name: rsa
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
          # Чекаутим код
          - uses: actions/checkout@master
            # Устанавливаем python нужной версии
          - uses: actions/setup-python@v3.11
            with:
              python-version: '3.11'
              architecture: 'x64'
          - name: Install requirements
            # Устанавливаем зависимости
            run: pip install cryptography
          - name: Run tests
            run: coverage run ./testing.py
          - name: Tests report
            run: coverage report